//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Saving.CriteriaIReport.u_cri_coopid_date_rloantype_rmembgroup_rcountdate {
    
    
    public partial class u_cri_coopid_date_rloantype_rmembgroup_rcountdate {
        
        /// <summary>
        /// ReportName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label ReportName;
        
        /// <summary>
        /// dsMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Saving.CriteriaIReport.u_cri_coopid_date_rloantype_rmembgroup_rcountdate.DsMain dsMain;
    }
}
