//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Saving.Applications.assist.dlg.wd_as_request_memberno_ctrl {
    
    
    public partial class wd_as_request_memberno {
        
        /// <summary>
        /// dsList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Saving.Applications.assist.dlg.wd_as_request_memberno_ctrl.DsList dsList;
        
        /// <summary>
        /// LbCount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label LbCount;
    }
}
